### ISSUE TITLE
Any simple tasks?

### ISSUE THREAD

**Issue by Le0nX** [ChimeHQ/Impact#3]
Hi! 
I would like to contribute. :) 
Do you have any novice friendly tasks?

**Comment by duncanwilcox** [comment]
Yeah me too. We chatted on CoreInt. Perhaps you can create a sort of a high level plan of the different components, both client and server, that you see becoming part of Impact?

**Comment by mattmassicotte** [comment]
This is great - I'm so happy to hear from both of you! There's lots of work, in many areas, so I'm sure we can find something that is of interest. Here are some areas, and suggestions of work.

Report quality:
- I think I'd like to keep the "[Topic:Details]" formatting for log entries, but I broke that scheme for debug logging. Fixing that should be easy.
- The "[Thread:Crashed]" concept is weird. I'd like to come up with something better for communicating that a thread has crashed. 
- The time of the report launch, as well as crash events, are not recorded. This is probably something people will want.

Working towards iOS support:
- Put it into an iOS app, run on a real device and see what doesn't work.
- Investigate if what's being done to test real crashes for macOS apps is possible for iOS apps too

Testing infrastructure:
- It would be great to build a log parser. This will greatly improve the quality of testing, and would helpful for post-processing as well. Hard to say if this should be part of the Impact library itself, or a companion lib.

Stack unwinding still requires a lot of work, but this will require a lot of low-level C work. It's absolutely doable, but probably isn't a beginner task. NSExceptions/C++ exceptions also aren't supported, which is less low-level, but still in the guts if that's interesting.

As for client/server parts, right now, I guess I'd like to hear ideas. Impact doesn't have any on-disk report management or networking. For my app, I've build that myself. But, how it works depends a lot on what's needed by the developer. Server-side stuff is much more complex, since you'll need a lot of infrastructure to get a minimal system working. But, I'd be happy to discuss those pieces. It would be helpful to know how current self-hosted systems, work. I'm not really familiar with them.

**Comment by mattmassicotte** [comment]
@Le0nX if you want more help picking something, let me know. And, if none of these seem good to you, we can come up with others.

@duncanwilcox I've thought a bit more about your question. A full crash reporting stuff, roughly, has four parts:

- SDK backend (capturing crashes)
- SDK front-end (developer-facing APIs, networking, file management, post-processing)
- Server (accepting reports, symbolication, analysis, storage, email, issue tracker integration etc)
- UI (viewing crash data)

Today, Impact is really just a backend. It leaves all other parts up to its users. But, perhaps as a first step, we could take some inspiration from https://github.com/CleanCocoa/CrashReporter. Basically, a dedicated, modular SDK front-end. This appeals to me for a few reasons.

It continues the small, focused library feel. By being decoupled from Impact itself, it makes it possible for developers to expand their reports to include logging or whatever else they might be interested in. It would also allow for all the cool stuff that CleanCocoa's CrashReporter does, like relaying the OS's ReportCrash logs, and for end-user UI. Of course, it could come with a Impact module out of the box, so that could just work with a line or two of code.

Thoughts?

**Comment by Le0nX** [comment]
Sounds very interesting! I'm interested mostly in iOS devices. 
Have a lot of experience in c/c++, but would like to improve my swift/obj-c skills.

**Comment by mattmassicotte** [comment]
Ok perfect! Impact is mostly C, but has a little ObjC in there.

You can technically install it via Carthage. Or, manually if that's not your thing. It would be interesting to start by running it in the iOS simulator for a 64bit device. That will most closely match the supported configuration for macOS. From there, we can start figuring out what areas need to be fixed/improved. Then, we can look at arm64 support.

**Comment by mattmassicotte** [comment]
Going to close this issue, as it's been hanging around for a while. But, now that arm64 support is here, things are working well on iOS too :)
