### ISSUE TITLE
KSCrash

### ISSUE THREAD

**Issue by mickeyl** [ChimeHQ/Impact#4]
Thanks for this interesting new project in a space that's often overlooked.

Being a satisfied user with [KSCrash](https://github.com/kstenerud/KSCrash), which has served me well for many years – and it being used as the backend for at least one commercial crash reporting tool (Sentry) – I wonder how Impact relates to this.

I.e., did you have a look at KSCrash and considered using it as a starting point?

**Comment by mattmassicotte** [comment]
That's a great question! Yes, I was aware of KSCrash.

At it's core, Impact is a crash capturing library, not a crash reporter. It is specifically made to be a building block for a full reporter system. So, while KSCrash and Impact are very similar and have quite a bit of overlap, they are really serving different purposes. Some other notable differences on the crash capturing side:

Impact is built around a corruption-resistant file format. Corruption-resistance was an absolutely essential component in improving the reliability of the Crashlytics system. Impact's format is event more robust than the one used there. I'm not sure how KSCrash handles report corruption.

Impact has support for both Compact Unwind and DWARF CFI unwinding. Practically speaking, this is only essential for x86_64 (and i386, but Impact doesn't support that architecture currently). It's nice for arm64, and does produce slightly higher-quality stack traces there. But, arm64 is not as negatively impacted by simpler unwinding approaches.

Compact Unwind/DWARF notwithstanding, Impact does less work at crash time. This is by design, to minimize the likelihood of post-crash failure.

**Comment by mickeyl** [comment]
Thanks for your quick response. I agree that minimizing the amount of work being done at crash time is vital. KSCrash seems to be a bit neglected the last years, so in particular with the outlook of Apple Silicon, I'm looking for an alternative. I will test-drive Impact soon. Thanks again!
