### ISSUE TITLE
Can I use Impact within a binary framework?

### ISSUE THREAD

**Issue by mnive93** [ChimeHQ/Impact#7]
Want to enable crash capture system in our framework which will then report these crashes to our backend. 

We just want to be able to capture the crash and check if this crash is originating from our framework. Is that possible?

Our framework will then be used within multiple apps which might have third party crash reporting engines integrated. 
Will this work along with other crash reporting engines ?

**Comment by mattmassicotte** [comment]
Hello! Great questions.

First, about using in a framework. I answered this question on stack overflow here: https://stackoverflow.com/questions/50867813/crash-analyzing-tool-in-framework/51294888#51294888. The very brief summary is no, you cannot do this successfully with Impact or any other in-process reporting tool. Crashes are inherently a process-wide phenomenon. If you try, not only will it not work as you'd like, but it could also compromise reporting for any app that uses it. This is related to your second question.

Impact is not 100% guaranteed safe to use with other crash reporting frameworks. The reason, basically, that is not possible to do. Some crash reporting libraries claim they offer that safety, and it can be approximated. But, it is not possible to both instrument a process for crashes and also not change the state of the process in a way that could affect other reporting systems negatively. I have worked with multiple reporting installations extensively, and ultimately gave up, because there's no way to do it and even trying is a compromise.

Sorry for the bad news, but thanks for the questions!
